In [6]:
# 연습1-1
import numpy as np
print('연습')

arr = np.loadtxt("./data/seoul.csv", delimiter=',', skiprows=1, 
                 dtype=np.object)
#print(arr)

for row in arr:
    if row[4] == '':
        row[4] = -999
    if row[3] == '':
        row[3] = 999
    if row[2] == '':
        row[2] = -999
    row[4] = float(row[4])
    row[3] = float(row[3])
    row[2] = float(row[2])
print(arr)

max_temp = 0
max_temp_date = ''
for i in arr:
    if i[4] > max_temp:
        max_temp_date = i[0]
        max_temp = i[4]
print('서울 최고로 더웠던 날 : ', max_temp_date)
print('최고기온 : ', max_temp)
    

연습
[['1907-10-01' '108' 13.5 7.9 20.7]
 ['1907-10-02' '108' 16.2 7.9 22.0]
 ['1907-10-03' '108' 16.2 13.1 21.3]
 ...
 ['2020-09-05' '108' 23.3 19.2 27.3]
 ['2020-09-06' '108' 21.7 19.5 24.4]
 ['2020-09-07' '108' 19.2 17.5 20.6]]
서울 최고로 더웠던 날 :  2018-08-01
최고기온 :  39.6


In [13]:
# 연습1-2
print(arr)

ilgyocha_max_temp = 0
ilgyocha_temp_date = ''
ilgyocha = 1
for i in arr:
    ilgyocha = i[4]-i[3]
    if ilgyocha > ilgyocha_max_temp:
        ilgyocha_temp_date = i[0]
        ilgyocha_max_temp = ilgyocha

print('서울 최고로 일교차 큰 날 : ', ilgyocha_temp_date)
print('최고 일교차 : ', ilgyocha_max_temp)

[['1907-10-01' '108' 13.5 7.9 20.7]
 ['1907-10-02' '108' 16.2 7.9 22.0]
 ['1907-10-03' '108' 16.2 13.1 21.3]
 ...
 ['2020-09-05' '108' 23.3 19.2 27.3]
 ['2020-09-06' '108' 21.7 19.5 24.4]
 ['2020-09-07' '108' 19.2 17.5 20.6]]
서울 최고로 일교차 큰 날 :  1942-04-19
최고 일교차 :  21.8


In [14]:
# 연습1-3
print(arr)
# split('-')


# 월,일:04-29
# 평균일교차:12


[['1907-10-01' '108' 13.5 7.9 20.7]
 ['1907-10-02' '108' 16.2 7.9 22.0]
 ['1907-10-03' '108' 16.2 13.1 21.3]
 ...
 ['2020-09-05' '108' 23.3 19.2 27.3]
 ['2020-09-06' '108' 21.7 19.5 24.4]
 ['2020-09-07' '108' 19.2 17.5 20.6]]


In [18]:
# 연습1-4
print(arr)
arr_daegu = np.loadtxt("./data/daegu.csv", delimiter=',', skiprows=1, 
                 dtype=np.object)

for row in arr_daegu:
    if row[4] == '':
        row[4] = -999
    row[4] = float(row[4])
print(arr_daegu)
print(arr.size)
print(arr_daegu.size)

[['1907-10-01' '108' 13.5 7.9 20.7]
 ['1907-10-02' '108' 16.2 7.9 22.0]
 ['1907-10-03' '108' 16.2 13.1 21.3]
 ...
 ['2020-09-05' '108' 23.3 19.2 27.3]
 ['2020-09-06' '108' 21.7 19.5 24.4]
 ['2020-09-07' '108' 19.2 17.5 20.6]]
[['1907-01-31' '143' '' '-7' 0.8]
 ['1907-02-01' '143' '' '' -999.0]
 ['1907-02-02' '143' '' '' -999.0]
 ...
 ['2020-09-05' '143' '19.9' '17.3' 23.1]
 ['2020-09-06' '143' '19.5' '17.6' 20.7]
 ['2020-09-07' '143' '23.4' '18.8' 25.6]]
204100
207470


In [41]:
# 연습2-1
arr_movie_rating = np.loadtxt("./data/ratings.csv", delimiter=',', 
                              skiprows=1, dtype=np.object)
for row in arr_movie_rating:
    row[0] = int(row[0])
    row[3] = float(row[3])
    row[2] = float(row[2])
    row[1] = float(row[1])
print(arr_movie_rating)

t_array = arr_movie_rating.T
print('전체 평점 평균 : ', np.mean(t_array[2]))  # 평균

[[1 1.0 4.0 964982703.0]
 [1 3.0 4.0 964981247.0]
 [1 6.0 4.0 964982224.0]
 ...
 [610 168250.0 5.0 1494273047.0]
 [610 168252.0 5.0 1493846352.0]
 [610 170875.0 3.0 1493846415.0]]
전체 평점 평균 :  3.501556983616962


In [55]:
# 연습2-2
list_userid = []
for j in arr_movie_rating:
    list_userid.append(j[0])
# print(list_userid)
list_userid = set(list_userid)
print(list_userid)
print(len(list_userid))

countlist = [0]*610
sumlist = [0]*610
print(len(sumlist))
# print(countlist)
for k in list_userid:
    for m in arr_movie_rating:
        if k == m[0]:
            sumlist[k-1] = sumlist[k-1] + m[2]
            countlist[k-1] = countlist[k-1] + 1
    sumlist[k-1] = sumlist[k-1] / countlist[k-1]
# print(sumlist)  # 유저별 평균평점
for k in list_userid:
    print('유저 넘버 : ', k, ', 얘가 남긴 평균평점 : ', sumlist[k-1])

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

유저 넘버 :  477 , 얘가 남긴 평균평점 :  3.736666666666667
유저 넘버 :  478 , 얘가 남긴 평균평점 :  2.8181818181818183
유저 넘버 :  479 , 얘가 남긴 평균평점 :  3.320441988950276
유저 넘버 :  480 , 얘가 남긴 평균평점 :  3.27511961722488
유저 넘버 :  481 , 얘가 남긴 평균평점 :  2.806451612903226
유저 넘버 :  482 , 얘가 남긴 평균평점 :  3.40625
유저 넘버 :  483 , 얘가 남긴 평균평점 :  3.618818681318681
유저 넘버 :  484 , 얘가 남긴 평균평점 :  3.8145454545454545
유저 넘버 :  485 , 얘가 남긴 평균평점 :  3.869565217391304
유저 넘버 :  486 , 얘가 남긴 평균평점 :  4.017857142857143
유저 넘버 :  487 , 얘가 남긴 평균평점 :  3.142857142857143
유저 넘버 :  488 , 얘가 남긴 평균평점 :  3.8828828828828827
유저 넘버 :  489 , 얘가 남긴 평균평점 :  3.017746913580247
유저 넘버 :  490 , 얘가 남긴 평균평점 :  3.15929203539823
유저 넘버 :  491 , 얘가 남긴 평균평점 :  4.15625
유저 넘버 :  492 , 얘가 남긴 평균평점 :  3.8677685950413223
유저 넘버 :  493 , 얘가 남긴 평균평점 :  3.6885245901639343
유저 넘버 :  494 , 얘가 남긴 평균평점 :  4.2272727272727275
유저 넘버 :  495 , 얘가 남긴 평균평점 :  4.009433962264151
유저 넘버 :  496 , 얘가 남긴 평균평점 :  3.413793103448276
유저 넘버 :  497 , 얘가 남긴 평균평점 :  3.5686274509803924
유저 넘버 :  498 , 얘가 남긴 평균평점 : 

In [36]:
# 연습2-3
# arr_movie_name = np.loadtxt("./data/movies.csv", delimiter=',', 
#                               skiprows=1, dtype=np.object)
# print(arr_movie_name)